---

- name: Install nginx (APT)
  apt:
    pkg: nginx-{{ nginx_flavor }}
  notify:
    - restart nginx

- name: Disable default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - reload nginx

- name: Template nginx config file
  template:
    src: apt-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    backup: yes
  notify:
    - restart nginx
    - supervisorctl restart nginx
  become: yes
