---
# main tasks file for galaxyprojectdotorg.nginx

# Install from apt
- include: apt.yml
  when: nginx_flavor in [ 'core', 'light', 'full', 'extras' ]

- name: Install vhost configs
  template: src=templates/nginx/{{ item }}.j2 dest={{ nginx_local_conf_dir }}/sites-available/{{ item }} mode=0444 backup=yes
  with_items: nginx_configs
  notify:
    - reload nginx

- name: Enable vhosts
  file: dest={{ nginx_local_conf_dir }}/sites-enabled/{{ item }} src={{ nginx_local_conf_dir }}/sites-available/{{ item }} state=link
  with_items: nginx_configs
  notify:
    - reload nginx

- name: Set additional config options
  template: src=http_options.conf.j2 dest={{ nginx_local_conf_dir }}/conf.d/http_options.conf mode=0444 backup=yes
  when: nginx_conf_http is defined
  notify:
    - restart nginx

- name: Configure server-wide SSL
  template: src=ssl.conf.j2 dest={{ nginx_local_conf_dir }}/conf.d/ssl.conf mode=0444 backup=yes
  when: nginx_conf_ssl_certificate is defined and nginx_conf_ssl_certificate_key is defined
  notify:
    - restart nginx

- name: Create SSL directories
  file: path={{ item | dirname }} state=directory mode=0755
  with_items:
    - "{{ nginx_conf_ssl_certificate }}"
    - "{{ nginx_conf_ssl_certificate_key }}"
  when: nginx_conf_ssl_certificate is defined and nginx_conf_ssl_certificate_key is defined

- name: Install SSL certificate
  copy: src={{ nginx_ssl_src_dir }}/{{ nginx_conf_ssl_certificate | basename }} dest={{ nginx_conf_ssl_certificate }}
  when: nginx_conf_ssl_certificate is defined

- name: Install SSL private key
  copy:
    content: "{{ sslkeys[nginx_conf_ssl_certificate_key | basename] }}"
    dest: "{{ nginx_conf_ssl_certificate_key }}"
    mode: 0400
  when: nginx_conf_ssl_certificate_key is defined
